[package]
name = "rust-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = {version="0.49.0", features = ["full"]}
async-std = {version="1.12.0", features = ["attributes"]}